# Generated by Django 3.1.6 on 2021-02-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210205_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
