# Generated by Django 3.1.6 on 2021-02-07 22:03

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210205_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
