# Generated by Django 3.1.6 on 2021-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210207_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown',
        ),
    ]
