# Generated by Django 3.1.6 on 2021-02-07 23:53

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
