# Generated by Django 3.1.6 on 2021-02-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210207_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown',
        ),
    ]
