# Generated by Django 3.1.7 on 2021-02-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210217_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(max_length=225),
        ),
    ]
