# Generated by Django 3.1.6 on 2021-02-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='updated',
            new_name='update',
        ),
    ]
